[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./node_modules/.bin/prisma migrate deploy && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
