[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node node_modules/prisma/build/index.js migrate deploy && PORT=${PORT:-3000} node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
